dc/core/app/urls.py
from django.urls import path  
from .views import contact 

app_name = 'app'

urlpatterns = [
    path('', contact, name='contact-us'),
]

dc/core/services/urls.py
from django.urls import path  
from .views import all_services,webhosting,flavours,category

app_name = 'services'

urlpatterns = [
    path('all_services/<int:servicetype>/', all_services, name='all_services'),
    path('flavours/<int:index>/',  flavours, name='flavours'),
    path('category/<int:index>/',  category, name='category'),
    path('webhosting/', webhosting, name='webhosting'),
    
    
]

dc/dc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.app.views import landing_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='index'),
    path('contact/', include('core.app.urls', namespace='core.app')),
    path('summernote/', include('django_summernote.urls')),
    path('services/', include('core.services.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dc/core/services/models.py
from tabnanny import verbose
from django.db import models
from django.utils.safestring import mark_safe
from simple_history.models import HistoricalRecords
from django.core.exceptions import ValidationError

BANDWITH = [('Unlimited Bandwidth','Unlimited Bandwidth'),('Unlimited Bandwidth','Unlimited Bandwidth'),('Unlimited Bandwidth','Unlimited Bandwidth'),
    ('300GB Bandwidth','300GB Bandwidth'),('400GB Bandwidth','400GB Bandwidth'),('500GB Bandwidth','500GB Bandwidth'),
    ('600GB Bandwidth','600GB Bandwidth'),('700GB Bandwidth','700GB Bandwidth'),('30TB Bandwidth','30TB Bandwidth')
    ]

SERVICES =[('Cloud Services','Cloud Services'),('Webhosting Services','Webhosting Services'),('Collocation','Collocation')]

COST_PERIOD =[('Month','Month'),('Year','Year')]

def Validate_disk_space(space):
    splinted = str(space).split('*')
    if str(space).isdecimal() == True:
        return space
    elif len(splinted)==2 and str(splinted[0]).isdecimal()==True and str(splinted[1]).isdecimal() ==True:
        return space
    else:
        raise ValidationError('Space should be integer or  2*300 format')

class Common(models.Model):
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    history  =HistoricalRecords(inherit=True)
    
    class Meta:
        abstract = True

class Service(models.Model):
    name = models.CharField(max_length=30,choices=SERVICES,default=SERVICES[0],unique=True)# e.g Webhosting
    image = models.ImageField(upload_to='images')
    description = models.CharField(max_length=200)

    def image_path(self):
        if self.image:
            return mark_safe('<a href="%s"><img src="%s" style="width: 45px; height:45px;" /></a>' % (self.image.url,self.image.url))
    def image_path_only(self):
        if self.image:
            return str(self.image.url)

    
    def __str__(self):
        return str(self.name)


class Category(Common):
    service_name = models.ForeignKey(Service,on_delete=models.CASCADE)
    service_category  = models.CharField(max_length=50) #e.g vdi/Konza Basic Package
    image_file = models.ImageField(upload_to='images')
    description = models.CharField(max_length=500)

    class Meta:
        verbose_name_plural ='Categories'
    
    def image_path_only(self):
        if self.image_file:
            return str(self.image_file.url)

    
    def __str__(self):
        return str(self.service_category)

class ServiceType(Common):
    service_name = models.ForeignKey(Category,on_delete=models.CASCADE)
    service_type  = models.CharField(max_length=50) #e.g small/Konza Business Enterprise
    payment_period = models.CharField(max_length=10,choices=COST_PERIOD,default=COST_PERIOD[0])
    cost = models.FloatField(verbose_name='Cost (USD)')
    cpu_type = models.CharField(max_length=6,choices=[('CPU','CPU'),('VCPU','VCPU')],default='VCPU')
    cpu  = models.CharField(max_length=10)
    memory_unit = models.CharField(max_length=4,choices=[('MB','MB'),('GB','GB')],default='GB')
    memory  = models.FloatField()
    disk_type = models.CharField(max_length=15,choices=[('SYSTEM DISK','SYSTEM DISK'),('SAS','SAS')],default='SYSTEM DISK')
    disk  = models.CharField(max_length=15,verbose_name='DISK (GB)')
    bandwidth = models.CharField(max_length=50,choices=BANDWITH,default=BANDWITH[0])

    def __str__(self):
        return str(self.service_name)

dc/core/services/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Service,Category,ServiceType

def all_services(request,servicetype):
    context = {}
    service = Service.objects.get(name='Cloud Services')
    category = Category.objects.filter(service_name_id=service.id)
    sub_category = ServiceType.objects.all()
    context['service'],context['category'],context['sub_category']= service,category,sub_category
    context['level'] = 1
    return render(request=request,template_name='categories.html',context=context)

def category(request,index):
    context = {}
    service = Category.objects.get(id=index)
    context['previous'] = Service.objects.get(id=service.service_name_id).name
    category = ServiceType.objects.filter(service_name_id=service.id)
    context['service'],context['category']= service,category
    context['level'] = 2
    return render(request=request,template_name='categories.html',context=context)
    print(index)

def flavours(request):
    context = {}
    service = Service.objects.get(name='Cloud Services')
    category = Category.objects.filter(service_name_id=service.id)
    sub_category = ServiceType.objects.all()
    context['service'],context['category'],context['sub_category']= service,category,sub_category
    context['level'] = 1
    return render(request=request,template_name='categories.html',context=context)

def webhosting(request):
    context = {}
    service = Service.objects.get(name='Webhosting Services')
    category = Category.objects.filter(service_name_id=service.id)
    sub_category = ServiceType.objects.all()
    context['service'],context['category'],context['sub_category']= service,category,sub_category
    return render(request=request,template_name='services_base.html',context=context)

dc/core/services/templates/categories.html
{% extends "services_base.html" %}
{% load static %}
{% block title %}{{title}}{% endblock %}
{% block topcontent %}
{% if level == 1%}
<div class="bannen_inner">
      <div class="container">
          <div class="row marginii">
              <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                  <h1 class="web_text" style="padding-top: 60px;"><span class="color">{{ service.name }}</span></h1>
                  <p class="donec_text"> {{ service.description }}</p>
                   </div>
           <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
           <div class="img-box">
              <figure><img src="{{ service.image.url }}" alt="img" style="max-width: 100%;"></figure>
           </div>
      </div>
     </div>
     <div class="emaim-bt">
         <div class="col-md-9 margin-0">
      <div class="input-group mb-3 margin-top-20">
          <input type="text" class="form-control" placeholder="Enter domain name here">
      <div class="input-group-append">
          <button class="search_bt" type="Subscribe"><a href="#">Search</a></button>  
      </div>
      </div>           
  </div>
 </div>
</div>
</div>
{% else %}
<div class="bannen_inner">
    <div class="container">
        <div class="row marginii">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <h1 class="web_text" style="padding-top: 60px;"><span class="color">{{ service.service_category }}</span></h1>
                <p class="donec_text"> {{ service.description }}</p>
                 </div>
         <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
         <div class="img-box">
            <figure><img src="{{ service.image_file.url }}" alt="img" style="max-width: 100%;"></figure>
         </div>
    </div>
   </div>
   <div class="emaim-bt">
       <div class="col-md-9 margin-0">
    <div class="input-group mb-3 margin-top-20">
        <input type="text" class="form-control" placeholder="Enter domain name here">
    <div class="input-group-append">
        <button class="search_bt" type="Subscribe"><a href="#">Search</a></button>  
    </div>
    </div>           
</div>
</div>
</div>
</div>
{% endif %}
{% endblock %}
{% block bottomcontent %}
{% if level == 1%}
<div class="choose_section_2">
    	<div class="container">
            <div class="row">
                <h1 class="web_text" style="padding-top: 60px;"><span class="color">{{ service.name }}  Categories </span></h1>
            </div>
    	    <div class="row"> 
                {% for cat in category %}
    		    <div class="col-sm-4">
    			    <div class="about_inner">
    				    <div class="icon"><a href="#"><img src="{% static 'images/icon-1.png' %}"></a></div>
    				    <h2 class="totaly_text">{{forloop.counter}}. {{ cat.service_category }}</h2>
    				    <p class="making"> {{ cat.description }}</p>
    			    </div>
					<div>
						<button class="read_more"><a href="{% url 'services:category' cat.id %}">Read More</a></button>
					</div>  
    		    </div>
                {% endfor %}
    		    
    	    </div>    		
    	</div>
</div>
{% else %}
<div class="choose_section_2">
    <div class="container">
        <div class="row">
            <h1 class="web_text" style="padding-top: 60px;"><span class="color">{{ service.service_category }}  Flavours </span></h1>
        </div>
            <div class="col-md-12">
                <div class="row">
                    <div class="table-responsive">
                        <table class="table table-striped custom-table">
                          <thead>
                            <tr style="background-color: green;">
                              <th scope="col" style="color: white;">No.</th>
                              <th scope="col" style="color: white;">Type</th>
                              <th scope="col" style="color: white;">CPU</th>
                              <th scope="col" style="color: white;">Memory</th>
                              <th scope="col" style="color: white;">Storage</th>
                              <th scope="col" style="color: white;">Bandwidth</th>
                              <th scope="col" style="color: white;">Price</th>
                              <th scope="col" style="color: white;">Add to Cart</th>
                            </tr>
                          </thead>
                          <tbody>
                            
                                {% for cat in category %}
                                <tr scope="row">
                                    <td>{{forloop.counter}}</td>
                                    <td>{{cat.service_type}}</td>
                                    <td><b>{{cat.cpu}}</b> {{cat.cpu_type}}</td>
                                    <td><b>{{cat.memory}}</b> {{cat.memory_unit}}</td>
                                    <td><b>{{cat.disk}}</b> {{cat.disk_type}}</td>
                                    <td>{{ cat.bandwidth }}</td>
                                    <td><b>${{cat.cost}}/</b> {{cat.payment_period}}</td>
                                    <td><button class="read_more"><a href="{% url 'services:flavours' cat.id %}">Add to Cart</a></button></td>
                                </tr>
                                {% endfor %}
                          </tbody>
                        </table>
                      </div>
                </div>
            
        </div>    		
    </div>
</div>
{% endif %}
{% endblock %}
   

dc/core/services/templates/services_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<!-- basic -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- mobile metas -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="initial-scale=1, maximum-scale=1">
<!-- site metas -->
<title>{% block title %}{% endblock %}</title>
<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content="">	
<!-- bootstrap css -->
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<!-- style css -->
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<!-- Responsive-->
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
<!-- fevicon -->
<link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
<!-- Scrollbar Custom CSS -->
<link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
<!-- Tweaks for older IEs-->
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
<!-- owl stylesheets --> 
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">


<style>
	
	
	.dropdown {
	  position: relative;
	  display: inline-block;
	}
	
	.dropdown-content {
	  display: none;
	  position: absolute;
	  background-color: #181818;
	  min-width: 160px;
	  z-index: 1;
	}
	
	.dropdown-content a {
	  color: black;
	  padding: 12px 16px;
	  text-decoration: none;
	  display: block;
	}
	
	.dropdown-content a:hover {background-color: #ddd;}
	
	.dropdown:hover .dropdown-content {display: block;}
	
	.dropdown:hover .dropbtn {background-color: #3e8e41;}
	</style>

</head>
<body>
	<header id="home"class="section">
	<div class="header_main">
         <!-- header inner -->
         <div class="header">
            <div class="container">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo"><a href="{% url 'index' %}"><img src="{% static 'images/dc-logo.png' %}" style="max-width: 30%;"></a> 
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                     <div class="menu-area">
                        <div class="limit-box">
                           <nav class="main-menu">
                              <ul class="menu-area-main">
                                 <li><a href="{% url 'index' %}">Home</a></li>
                                 <li><a href="#about">About</a></li>
								 <li>
									<div class="dropdown">
										<a class="dropbtn" style="color: white;">Services 
										  <i class="fa fa-caret-down"></i>
										</a>
										<div class="dropdown-content">
										  <a href="#">Cloud Services</a>
										  <a href="#">Webhosting Services</a>
										  <a href="#">Collocation</a>
										</div>
									  </div> 
								 </li>
                                 <li><a href="#testimonial">Testimonial</a></li>
                                 <li><a href="{% url 'app:contact-us' %}">Contact Us</a></li>
                              </ul>
                           </nav>
                        </div>
                     </div>
                 </div>
               </div>
            </div>
         </div>
	</header>
    <!-- banner end -->

    <!-- choose start -->
	{% block topcontent %}{% endblock %}
	{% block bottomcontent %}{% endblock %}
    <!-- contact start -->
    <div id="contact" class="contact_section">
    	<div class="container">
    		<div class="col-sm-12">
    			<h1 class="choose_text">Request A Call  Back</h1>
    			<p class="lorem_text">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour</p>
    		</div>
    	</div>
    </div>
    <div class="contact_section_2">
    	<div class="container">
    		<div class="row">
    			<div class="col-md-6">
    				<div class="input_main">
                       <div class="container">
                          <form  method="post">
							  {% csrf_token %}
								{% if form.erors %}
									{% for error in errors %}
									<div class="alert alert-danger" role="alert">
										{{ error }}
									  </div>
									{% endfor %}
								{% endif %}
                            {% comment %} <div class="form-group">
                              <input type="text" class="email-bt" placeholder="Name" name="Name">
                            </div>
                            <div class="form-group">
                              <input type="text" class="email-bt" placeholder="Email" name="Email">
                            </div>
                            <div class="form-group">
                              <input type="text" class="email-bt" placeholder="Phone" name="Email">
                            </div>
                                <div class="form-group">
                                  <textarea class="massage-bt" placeholder="Massage" rows="5" id="comment" name="text"></textarea>
                                </div> {% endcomment %}
                            </form>
                          
                       </div> 
                       <div class="send_btn">
                        <button type="button" class="main_bt"><a href="{% url 'app:contact-us' %}">Send</a></button>
                       </div>                   
                    </div>
    			</div>
    			<div class="col-md-6">
    				<div class="section_right">
    					<img src="{% static 'images/img-2.png' %}" style="max-width: 100%;">
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
    <div class="contact_section_3">
    	<div class="container">
    		<div class="contact_taital">
    			<div class="row web">
    				<div class="col-sm-12 col-md-12 col-lg-4">
    					<div class="map_main">
    						<img src="{% static 'images/map-icon.png' %}">
    						<span class="londan_text">Konza Technopolis, 7th floor, Konza Complex</span>
    					</div>
    				</div>
    				<div class="col-sm-6 col-md-6 col-lg-4">
    					<div class="map_main">
    						<img src="{% static 'images/phone-icon.png' %}">
    						<span class="londan_text">+254 20 434 3014
							</span>
    					</div>
    				</div>
    				<div class="col-sm-6 col-md-6 col-lg-4">
    					<div class="map_main">
    						<img src="{% static 'images/email-icon.png' %}">
    						<span class="londan_text">cloud@konza.go.ke</span>
    					</div>
    				</div>
    			</div>
    		</div>
    		<div class="contact_product">
    			<div class="row">
    				<div class="col-sm-6 col-md-6 col-lg-2">
    					<div class="footer-logo"><img src="{% static 'images/dc-logo.png' %}" style="max-width: 100%;"></div>
    				</div>
    				<div class="col-sm-6 col-md-6 col-lg-4">
    					<h1 class="useful_text">USEFUL LINK</h1>
    				<div class="menu">
    					<ul>
    						<li><a href="#home"><img src="images/bulit-icon.png" style="padding-right: 10px;">Home</a></li>
    						<li><a href="#about"><img src="images/bulit-icon.png" style="padding-right: 10px;">About</a></li>
    						<li><a href="#service"><img src="images/bulit-icon.png" style="padding-right: 10px;">Services</a></li>
    						<li><a href="#contact"><img src="images/bulit-icon.png" style="padding-right: 10px;">Contact Us</a></li>
    					</ul>
    				</div>	
    				</div>
    				<div class="col-sm-12 col-md-12 col-lg-6">
    					<h1 class="useful_text">PRODUCT</h1>
    					<div class="menu multi_column_menu">
    					   <ul>
    						  <li class="footer_menu"><a href="#"><img src="{% static 'images/bulit-icon.png' %}" class="footer_menu">Webhosting</a></li>
    						  <li class="footer_menu"><a href="#"><img src="{% static 'images/bulit-icon.png' %}" class="footer_menu">Reseler Hosting</a></li>
    						  <li class="footer_menu"><a href="#"><img src="{% static 'images/bulit-icon.png' %}" class="footer_menu">VPS Hosting</a></li>
    						  <li class="footer_menu"><a href="#"><img src="{% static 'images/bulit-icon.png' %}" class="footer_menu">Wordpress Hosting</a></li>
    						  <li class="footer_menu"><a href="#"><img src="{% static 'images/bulit-icon.png' %}" class="footer_menu">Dedicated hosting</a></li>
    						  <li class="footer_menu"><a href="#"><img src="{% static 'images/bulit-icon.png' %}" class="footer_menu">Windows</a></li>
    					   </ul>
    				    </div>
    				    <div class="input-group mb-3 margin-top-30">
                           <input type="text" class="form-control" placeholder="Enter you email">
                           <div class="input-group-append">
                              <button class="subsrcibe_bt" type="submit"><a href="#">SUBSCRIBE</a></button>  
                           </div>
                        </div>
    				</div>
    			</div>
    		</div>
    		<div class="icon_main">
    			<div class="row">
    				<div class="col-sm-12">
    					<div class="menu_text">
    						<ul>
    						   <li><a href="#"><img src="{% static 'images/twitter-icon.png' %}"></a></li>
    						   <li><a href="#"><img src="{% static 'images/in-icon.png' %}"></a></li>
    						   <li><a href="#"><img src="{% static 'images/google-icon.png' %}"></a></li>
    					    </ul>
    					</div>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
    <div class="copyright_main">
    	<div class="container">
    		<p class="copy_text">© 2022 All Rights Reserved. <a href="https://konza.go.ke">Konza Technopolis</a></p>
    	</div>
    </div>


    <!-- contact end -->
    <!-- Javascript files-->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <script src="{% static 'js/plugin.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
      <!-- javascript --> 
      <script src="{% static 'js/owl.carousel.js' %}"></script>
      <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
      <script>
         $(document).ready(function(){
         $(".fancybox").fancybox({
         openEffect: "none",
         closeEffect: "none"
         });
         
         $(".zoom").hover(function(){
         
         $(this).addClass('transition');
         }, function(){
         
         $(this).removeClass('transition');
         });
         });
         </script> 
 
</body>
</html>